import './globals.css'
import { Inter } from 'next/font/google'
import Searchbar from './components/Searchbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'E-commerce Development Task',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Searchbar/>
        {children}
        </body>
    </html>
  )
}
